# Generated by Django 5.0.2 on 2024-02-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviewpost", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewmodel",
            old_name="userful_review_record",
            new_name="useful_review_record",
        ),
    ]
